version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DOCKER_ENVIRONMENT: "true"  # Set environment variable to indicate Docker environment
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
